<?php

include_once '../class/Manager.php';
$db = BD::connecter(); //CONNEXION A LA BASE DE DONNEE
$manager = new Manager($db); //CREATION D'UNE INSTANCE DU MANAGER




$test =
array(
array("mail"=>'agnes.bonvilain@imag.fr'),
	array("mail"=>'ahmad.bsiesy@cea.fr'),
	array("mail"=>'alain.girard@cea.fr'),
	array("mail"=>'alberto.ferrari@neel.cnrs.fr'),
	array("mail"=>'alexandre.reinhardt@cea.fr'),
	array("mail"=>'alice.nicolas@cea.fr'),
	array("mail"=>'alphonse.torres@cea.fr'),
	array("mail"=>'amelie.dussaigne@cea.fr'),
	array("mail"=>'amy.n-hari@cea.fr'),
	array("mail"=>'anne.ghis@cea.fr'),
	array("mail"=>'aurelia.plihon@cea.fr'),
	array("mail"=>'aurelie.tauzin@cea.fr'),
	array("mail"=>'aziz.zenasni@cea.fr'),
	array("mail"=>'balmes@esrf.fr'),
	array("mail"=>'bassem.salem@cea.fr'),
	array("mail"=>'benjamin.sacepe@neel.cnrs.fr'),
	array("mail"=>'bernard.dieny@cea.fr'),
	array("mail"=>'bernard.pelissier@cea.fr'),
	array("mail"=>'bernard.viala@cea.fr'),
	array("mail"=>'bertrand.chambion@cea.fr'),
	array("mail"=>'carmen.jimenez@grenoble-inp.fr'),
	array("mail"=>'catherine.dubourdieu@ec-lyon.fr'),
	array("mail"=>'catherine.pudda@cea.fr'),
	array("mail"=>'cecile.gourgon@cea.fr'),
	array("mail"=>'celine.ternon@grenoble-inp.fr'),
	array("mail"=>'christelle.laugier@cea.fr'),
	array("mail"=>'christian.seassal@ec-lyon.fr'),
	array("mail"=>'christophe.brun@cea.fr'),
	array("mail"=>'christophe.durand@cea.fr'),
	array("mail"=>'christopher.bauerle@grenoble.cnrs.fr'),
	array("mail"=>'claire.baraduc@cea.fr'),
	array("mail"=>'corinne.perret@cea.fr'),
	array("mail"=>'cyril.herrier@cea.fr'),
	array("mail"=>'david.cooper@cea.fr'),
	array("mail"=>'david.munoz-rojas@grenoble-inp.fr'),
	array("mail"=>'david.peyrade@cea.fr'),
	array("mail"=>'dominique.givord@grenoble.cnrs.fr'),
	array("mail"=>'elsa.lhotel@neel.cnrs.fr'),
	array("mail"=>'emmanuel.hadji@cea.fr'),
	array("mail"=>'emmanuel.picard@cea.fr'),
	array("mail"=>'emmanuelle.pauliac-vaujour@cea.fr'),
	array("mail"=>'erwine.pargon@cea.fr'),
	array("mail"=>'florence.podevin@grenoble-inp.fr'),
	array("mail"=>'franck.omnes@grenoble.cnrs.fr'),
	array("mail"=>'francois.boizot@cea.fr'),
	array("mail"=>'francois.boulard@cea.fr'),
	array("mail"=>'francois.lefloch@cea.fr'),
	array("mail"=>'ftemplier@cea.fr'),
	array("mail"=>'gilbert.reyne@g2elab.grenoble-inp.fr'),
	array("mail"=>'gilles.cunge@cea.fr'),
	array("mail"=>'gilles.gaudin@cea.fr'),
	array("mail"=>'gilles.lasfargues@cea.fr'),
	array("mail"=>'guillaume.belly@cea.fr'),
	array("mail"=>'helene.bea@cea.fr'),
	array("mail"=>'helene.joisten@cea.fr'),
	array("mail"=>'henri.mariette@cea.fr'),
	array("mail"=>'herve.boukari@neel.cnrs.fr'),
	array("mail"=>'Ibrahima.Gueye@cea.fr'),
	array("mail"=>'ionica@minatec.inpg.fr'),
	array("mail"=>'ivan-christophe.robin@cea.fr'),
	array("mail"=>'jean.dijon@cea.fr'),
	array("mail"=>'jean-herve.tortai@cea.fr'),
	array("mail"=>'jerome.faure-vincent@cea.fr'),
	array("mail"=>'joel.eymery@cea.fr'),
	array("mail"=>'jorgemario.herreramorales@cea.fr'),
	array("mail"=>'julien.borrel@cea.fr'),
	array("mail"=>'julien.claudon@cea.fr'),
	array("mail"=>'julien.tranchant@cnrs-imn.fr'),
	array("mail"=>'karim.vindasyassine@cea.fr'),
	array("mail"=>'karol.marty@cea.fr'),
	array("mail"=>'kuntheak.kheng@cea.fr'),
	array("mail"=>'laetitia.marty@neel.cnrs.fr'),
	array("mail"=>'laurent.vila@cea.fr'),
	array("mail"=>'Libor.Rufer@imag.fr'),
	array("mail"=>'Luis-miguel.FIDALGO@cea.fr'),
	array("mail"=>'marc.zelsmann@cea.fr'),
	array("mail"=>'marie-claire.cyrille@cea.fr'),
	array("mail"=>'maryse.reymermier@cea.fr'),
	array("mail"=>'melody.leclere@cea.fr'),
	array("mail"=>'michel.bouriau@ujf-grenoble.fr'),
	array("mail"=>'moira.hocevar@neel.cnrs.fr'),
	array("mail"=>'monfardini@grenoble.cnrs.fr'),
	array("mail"=>'morse@esrf.fr'),
	array("mail"=>'mouis@minatec.inpg.fr'),
	array("mail"=>'myriam.cubizolles@cea.fr'),
	array("mail"=>'nicolas.pauc@cea.fr'),
	array("mail"=>'nora.dempsey@grenoble.cnrs.fr'),
	array("mail"=>'norbert.moussy@cea.fr'),
	array("mail"=>'olivier.buisson@neel.cnrs.fr'),
	array("mail"=>'olivier.hignette@esrf.fr'),
	array("mail"=>'olivier.joubert@cea.fr'),
	array("mail"=>'patrick.warin@cea.fr'),
	array("mail"=>'philippe.roche@grenoble.cnrs.fr'),
	array("mail"=>'pierre.thibault@ujf-grenoble.fr'),
	array("mail"=>'pierre-patrick.lassagne@cea.fr'),
	array("mail"=>'raphael.boichot@simap.grenoble-inp.fr'),
	array("mail"=>'renaud.viennet@grenoble-inp.fr'),
	array("mail"=>'roch.espiau-de-lamaestre@cea.fr'),
	array("mail"=>'roman.kramer@grenoble.cnrs.fr'),
	array("mail"=>'sebastien.barnola@cea.fr'),
	array("mail"=>'sebastien.boisseau@cea.fr'),
	array("mail"=>'sebastien.grousset@cea.fr'),
	array("mail"=>'sebastien.liatard@cea.fr'),
	array("mail"=>'sebastien.renet@cea.fr'),
	array("mail"=>'sebastien.solan@cea.fr'),
	array("mail"=>'silvano.defranceschi@cea.fr'),
	array("mail"=>'skandar.basrour@imag.fr'),
	array("mail"=>'stefania.pizzini@neel.cnrs.fr'),
	array("mail"=>'stephane.barnabe@cea.fr'),
	array("mail"=>'stephane.monfray@st.com'),
	array("mail"=>'stephane.pocas@cea.fr'),
	array("mail"=>'stephanie.gaugiran@cea.fr'),
	array("mail"=>'thibault@enerbee.fr'),
	array("mail"=>'thibaut.roux-marchand@univ-lyon1.fr'),
	array("mail"=>'thierry.baron@cea.fr'),
	array("mail"=>'thierry.chevolleau@cea.fr'),
	array("mail"=>'thierry.kretz@fr.thalesgroup.com'),
	array("mail"=>'tony.maindron@cea.fr'),
	array("mail"=>'tristan.meunier@grenoble.cnrs.fr'),
	array("mail"=>'ulrich.soupremanien@cea.fr'),
	array("mail"=>'ursula.ebels@cea.fr'),
	array("mail"=>'v.zwiller@tudelft.nl'),
	array("mail"=>'vdoering@ethz.ch'),
	array("mail"=>'vincent.artero@cea.fr'),
	array("mail"=>'vincent.consonni@grenoble-inp.fr'),
	array("mail"=>'virginie.brandli@crhea.cnrs.fr'),
	array("mail"=>'wiebke.guichard@grenoble.cnrs.fr'),
	array("mail"=>'wolfgang.wernsdorfer@neel.cnrs.fr'),
	array("mail"=>'xin.zhang@cea.fr'),
	array("mail"=>'yohan.desieres@cea.fr'),
	array("mail"=>'Yvan.Avenas@g2elab.grenoble-inp.fr'),
);			
		


for ($i = 0; $i < count($test); $i++) {    
    $doublon = (int) $manager->getSingle2("select count(idlogin) from loginpassword where  mail=?", $test[$i]['mail']);
    if($doublon>1){
        echo $test[$i]['mail'].' : '.$manager->getSingle2("select count(idlogin) from loginpassword where  mail=?", $test[$i]['mail']).'<br>';
    }
    
}