<?php

include	'../class/Manager.php';
//FERMETURE DE LA CONNEXION
$db	=	BD::connecter();
$manager	=	new	Manager($db);
include_once	'../outils/toolBox.php';


$arrayprojetphase2	=	array(
				array("refinterneprojet"	=>	"13-001",	"titre"	=>	"Pistes IEF",	"idutilisateur"	=>	19,	"idprojet"	=>	518),
				array("refinterneprojet"	=>	"13-002",	"titre"	=>	"CDXI",	"idutilisateur"	=>	400,	"idprojet"	=>	519),
				array("refinterneprojet"	=>	"13-003",	"titre"	=>	"Ex-MARMOTTE",	"idutilisateur"	=>	158,	"idprojet"	=>	520),
				array("refinterneprojet"	=>	"13-004",	"titre"	=>	"CellSec",	"idutilisateur"	=>	347,	"idprojet"	=>	521),
				array("refinterneprojet"	=>	"13-005",	"titre"	=>	"SPINHALL",	"idutilisateur"	=>	392,	"idprojet"	=>	522),
				array("refinterneprojet"	=>	"13-006",	"titre"	=>	"FLYELEC and QUSPINMOTION",	"idutilisateur"	=>	386,	"idprojet"	=>	523),
				array("refinterneprojet"	=>	"13-007",	"titre"	=>	"CEPLE",	"idutilisateur"	=>	208,	"idprojet"	=>	524),
				array("refinterneprojet"	=>	"13-008",	"titre"	=>	"SAG ZnO",	"idutilisateur"	=>	270,	"idprojet"	=>	525),
				array("refinterneprojet"	=>	"13-009",	"titre"	=>	"LP3D",	"idutilisateur"	=>	268,	"idprojet"	=>	526),
				array("refinterneprojet"	=>	"13-010",	"titre"	=>	"BOODI2",	"idutilisateur"	=>	381,	"idprojet"	=>	527),
				array("refinterneprojet"	=>	"13-011",	"titre"	=>	"SALINS",	"idutilisateur"	=>	372,	"idprojet"	=>	528),
				array("refinterneprojet"	=>	"13-012",	"titre"	=>	"Microéléctrodes diamant et nanostructures Si pour capteurs chimiques bio",	"idutilisateur"	=>	390,	"idprojet"	=>	529),
				array("refinterneprojet"	=>	"13-013",	"titre"	=>	"NanoQUARTETS",	"idutilisateur"	=>	206,	"idprojet"	=>	530),
				array("refinterneprojet"	=>	"13-014",	"titre"	=>	"Memristors",	"idutilisateur"	=>	164,	"idprojet"	=>	531),
				array("refinterneprojet"	=>	"13-015",	"titre"	=>	"Mecanix",	"idutilisateur"	=>	357,	"idprojet"	=>	532),
				array("refinterneprojet"	=>	"13-016",	"titre"	=>	"Composants photonique",	"idutilisateur"	=>	344,	"idprojet"	=>	533),
				array("refinterneprojet"	=>	"13-017",	"titre"	=>	"MERLIN",	"idutilisateur"	=>	366,	"idprojet"	=>	534),
				array("refinterneprojet"	=>	"13-018",	"titre"	=>	"Oxyde yttrium",	"idutilisateur"	=>	13,	"idprojet"	=>	535),
				array("refinterneprojet"	=>	"13-019",	"titre"	=>	"Spinnova Leti",	"idutilisateur"	=>	362,	"idprojet"	=>	536),
				array("refinterneprojet"	=>	"13-020",	"titre"	=>	"Spinnova Spintec",	"idutilisateur"	=>	156,	"idprojet"	=>	537),
				array("refinterneprojet"	=>	"13-021",	"titre"	=>	"CIFRE Renault",	"idutilisateur"	=>	342,	"idprojet"	=>	538),
				array("refinterneprojet"	=>	"13-022",	"titre"	=>	"Holoview",	"idutilisateur"	=>	211,	"idprojet"	=>	539),
				array("refinterneprojet"	=>	"13-023",	"titre"	=>	"Scanning micro Hall probe",	"idutilisateur"	=>	153,	"idprojet"	=>	540),
				array("refinterneprojet"	=>	"13-024",	"titre"	=>	"RECIPE",	"idutilisateur"	=>	204,	"idprojet"	=>	541),
				array("refinterneprojet"	=>	"13-025",	"titre"	=>	"COSMOS",	"idutilisateur"	=>	393,	"idprojet"	=>	542),
				array("refinterneprojet"	=>	"13-026",	"titre"	=>	"GMR Co nanoparticules",	"idutilisateur"	=>	387,	"idprojet"	=>	543),
				array("refinterneprojet"	=>	"13-027",	"titre"	=>	"ED1S",	"idutilisateur"	=>	378,	"idprojet"	=>	544),
				array("refinterneprojet"	=>	"13-028",	"titre"	=>	"GaAs solar",	"idutilisateur"	=>	394,	"idprojet"	=>	545),
				array("refinterneprojet"	=>	"13-029",	"titre"	=>	"GraFEn",	"idutilisateur"	=>	367,	"idprojet"	=>	546),
				array("refinterneprojet"	=>	"13-030",	"titre"	=>	"MATISSE",	"idutilisateur"	=>	145,	"idprojet"	=>	547),
				array("refinterneprojet"	=>	"13-031",	"titre"	=>	"THALES-1",	"idutilisateur"	=>	154,	"idprojet"	=>	548),
				array("refinterneprojet"	=>	"13-032",	"titre"	=>	"ALEDIA",	"idutilisateur"	=>	8,	"idprojet"	=>	549),
				array("refinterneprojet"	=>	"13-033",	"titre"	=>	"COC",	"idutilisateur"	=>	351,	"idprojet"	=>	550),
				array("refinterneprojet"	=>	"13-034",	"titre"	=>	"MOSAIC-UE",	"idutilisateur"	=>	362,	"idprojet"	=>	551),
				array("refinterneprojet"	=>	"13-035",	"titre"	=>	"SPOT",	"idutilisateur"	=>	362,	"idprojet"	=>	552),
				array("refinterneprojet"	=>	"13-036",	"titre"	=>	"INSCOOP",	"idutilisateur"	=>	339,	"idprojet"	=>	553),
				array("refinterneprojet"	=>	"13-037",	"titre"	=>	"HEATec - AIN",	"idutilisateur"	=>	230,	"idprojet"	=>	554),
				array("refinterneprojet"	=>	"13-038",	"titre"	=>	"Sport for memory",	"idutilisateur"	=>	392,	"idprojet"	=>	555),
				array("refinterneprojet"	=>	"13-039",	"titre"	=>	"IdTrac",	"idutilisateur"	=>	389,	"idprojet"	=>	556),
				array("refinterneprojet"	=>	"13-040",	"titre"	=>	"PC-LED",	"idutilisateur"	=>	159,	"idprojet"	=>	557),
				array("refinterneprojet"	=>	"13-041",	"titre"	=>	"Thèse CTBU nanofils piézo",	"idutilisateur"	=>	160,	"idprojet"	=>	558),
				array("refinterneprojet"	=>	"13-042",	"titre"	=>	"HANAS",	"idutilisateur"	=>	358,	"idprojet"	=>	559),
				array("refinterneprojet"	=>	"13-043",	"titre"	=>	"XDISPE",	"idutilisateur"	=>	358,	"idprojet"	=>	560),
				array("refinterneprojet"	=>	"13-044",	"titre"	=>	"RAMSES",	"idutilisateur"	=>	8,	"idprojet"	=>	561),
				array("refinterneprojet"	=>	"13-045",	"titre"	=>	"Projet photonique",	"idutilisateur"	=>	63,	"idprojet"	=>	562),
				array("refinterneprojet"	=>	"13-046",	"titre"	=>	"Solaforce",	"idutilisateur"	=>	8,	"idprojet"	=>	563),
				array("refinterneprojet"	=>	"13-047",	"titre"	=>	"Majorana",	"idutilisateur"	=>	398,	"idprojet"	=>	564),
				array("refinterneprojet"	=>	"13-048",	"titre"	=>	"SIPACK",	"idutilisateur"	=>	377,	"idprojet"	=>	565),
				array("refinterneprojet"	=>	"13-049",	"titre"	=>	"OxRRAM",	"idutilisateur"	=>	397,	"idprojet"	=>	566),
				array("refinterneprojet"	=>	"13-050",	"titre"	=>	"Dispositifs à base de graphène pour le champ proche",	"idutilisateur"	=>	264,	"idprojet"	=>	567),
				array("refinterneprojet"	=>	"13-051",	"titre"	=>	"Thèse Pompe Fluidique",	"idutilisateur"	=>	382,	"idprojet"	=>	568),
				array("refinterneprojet"	=>	"13-052",	"titre"	=>	"UJF Chaire excellence CNRS",	"idutilisateur"	=>	165,	"idprojet"	=>	569),
				array("refinterneprojet"	=>	"13-054",	"titre"	=>	"PEROVSKITES",	"idutilisateur"	=>	278,	"idprojet"	=>	570),
				array("refinterneprojet"	=>	"13-055",	"titre"	=>	"NANOSHARK-PTA",	"idutilisateur"	=>	340,	"idprojet"	=>	571),
				array("refinterneprojet"	=>	"13-056",	"titre"	=>	"ERC HYMAGINE",	"idutilisateur"	=>	340,	"idprojet"	=>	572),
				array("refinterneprojet"	=>	"13-057",	"titre"	=>	"ANR/PNANO MILESTONE",	"idutilisateur"	=>	156,	"idprojet"	=>	573),
				array("refinterneprojet"	=>	"13-058",	"titre"	=>	"J.FAURE-VINCENT",	"idutilisateur"	=>	145,	"idprojet"	=>	574),
				array("refinterneprojet"	=>	"13-061",	"titre"	=>	"ESPERADO-SPINTEC",	"idutilisateur"	=>	392,	"idprojet"	=>	575),
				array("refinterneprojet"	=>	"13-062",	"titre"	=>	"SUPERGRAPH",	"idutilisateur"	=>	207,	"idprojet"	=>	576),
				array("refinterneprojet"	=>	"13-063",	"titre"	=>	"HYBRIDNANO",	"idutilisateur"	=>	375,	"idprojet"	=>	577),
				array("refinterneprojet"	=>	"13-064",	"titre"	=>	"JoQOLaT",	"idutilisateur"	=>	363,	"idprojet"	=>	578),
				array("refinterneprojet"	=>	"13-065",	"titre"	=>	"WiQOJo",	"idutilisateur"	=>	363,	"idprojet"	=>	579),
				array("refinterneprojet"	=>	"13-066",	"titre"	=>	"SPSMS",	"idutilisateur"	=>	206,	"idprojet"	=>	580),
				array("refinterneprojet"	=>	"13-067",	"titre"	=>	"Grafonics",	"idutilisateur"	=>	22,	"idprojet"	=>	581),
				array("refinterneprojet"	=>	"13-069",	"titre"	=>	"CROCUS R&D-2",	"idutilisateur"	=>	370,	"idprojet"	=>	582),
				array("refinterneprojet"	=>	"13-070",	"titre"	=>	"PATHOS",	"idutilisateur"	=>	370,	"idprojet"	=>	583),
				array("refinterneprojet"	=>	"13-072",	"titre"	=>	"NAHDEVI",	"idutilisateur"	=>	139,	"idprojet"	=>	584),
				array("refinterneprojet"	=>	"13-073",	"titre"	=>	"Mosquitos",	"idutilisateur"	=>	404,	"idprojet"	=>	585),
				array("refinterneprojet"	=>	"13-075",	"titre"	=>	"HBS",	"idutilisateur"	=>	410,	"idprojet"	=>	586),
				array("refinterneprojet"	=>	"13-076",	"titre"	=>	"Mecanique et adhésion cellulaire",	"idutilisateur"	=>	175,	"idprojet"	=>	587),
				array("refinterneprojet"	=>	"13-077",	"titre"	=>	"Cyogenic platform nanodetectors",	"idutilisateur"	=>	384,	"idprojet"	=>	588),
				array("refinterneprojet"	=>	"13-078",	"titre"	=>	"NIKA",	"idutilisateur"	=>	384,	"idprojet"	=>	589),
				array("refinterneprojet"	=>	"13-079",	"titre"	=>	"Encapsulation d'OLED",	"idutilisateur"	=>	381,	"idprojet"	=>	590),
				array("refinterneprojet"	=>	"13-081",	"titre"	=>	"Nanosonar",	"idutilisateur"	=>	155,	"idprojet"	=>	591),
				array("refinterneprojet"	=>	"13-082",	"titre"	=>	"Cellbimpfinal",	"idutilisateur"	=>	361,	"idprojet"	=>	592),
				array("refinterneprojet"	=>	"13-083",	"titre"	=>	"Contrôle électrostatique de Mn dans boîtes quantiques CdTe/ZnTe",	"idutilisateur"	=>	271,	"idprojet"	=>	593),
				array("refinterneprojet"	=>	"13-084",	"titre"	=>	"Nanopiezo",	"idutilisateur"	=>	341,	"idprojet"	=>	594),
				array("refinterneprojet"	=>	"13-085",	"titre"	=>	"Nanotherma",	"idutilisateur"	=>	279,	"idprojet"	=>	595),
				array("refinterneprojet"	=>	"13-086",	"titre"	=>	"Nanostructures en diamant",	"idutilisateur"	=>	163,	"idprojet"	=>	596),
				array("refinterneprojet"	=>	"13-087",	"titre"	=>	"Mass Spec Sample Prep",	"idutilisateur"	=>	365,	"idprojet"	=>	597),
				array("refinterneprojet"	=>	"13-088",	"titre"	=>	"T2015",	"idutilisateur"	=>	341,	"idprojet"	=>	598),
				array("refinterneprojet"	=>	"13-089",	"titre"	=>	"NANOFUNCTION-PTA",	"idutilisateur"	=>	139,	"idprojet"	=>	599),
				array("refinterneprojet"	=>	"13-090",	"titre"	=>	"Contacting III-N nanowires",	"idutilisateur"	=>	373,	"idprojet"	=>	600),
				array("refinterneprojet"	=>	"13-091",	"titre"	=>	"INTREPID",	"idutilisateur"	=>	372,	"idprojet"	=>	601),
				array("refinterneprojet"	=>	"13-092",	"titre"	=>	"VITRAIL",	"idutilisateur"	=>	372,	"idprojet"	=>	602),
				array("refinterneprojet"	=>	"13-093",	"titre"	=>	"Nanocomposite",	"idutilisateur"	=>	208,	"idprojet"	=>	603),
				array("refinterneprojet"	=>	"13-096",	"titre"	=>	"ESPERADO",	"idutilisateur"	=>	287,	"idprojet"	=>	604),
				array("refinterneprojet"	=>	"13-097",	"titre"	=>	"SOLID",	"idutilisateur"	=>	331,	"idprojet"	=>	605),
				array("refinterneprojet"	=>	"13-098",	"titre"	=>	"Puissance GaN",	"idutilisateur"	=>	337,	"idprojet"	=>	606),
				array("refinterneprojet"	=>	"13-099",	"titre"	=>	"Micro-structured magnets for MEMS Cluster",	"idutilisateur"	=>	396,	"idprojet"	=>	607),
				array("refinterneprojet"	=>	"13-100",	"titre"	=>	"Micro-structured magnets for MEMS ANR",	"idutilisateur"	=>	396,	"idprojet"	=>	608),
				array("refinterneprojet"	=>	"13-101",	"titre"	=>	"NEP IV",	"idutilisateur"	=>	269,	"idprojet"	=>	609),
				array("refinterneprojet"	=>	"13-102",	"titre"	=>	"Nanostructures SiNaPS",	"idutilisateur"	=>	269,	"idprojet"	=>	610),
				array("refinterneprojet"	=>	"13-103",	"titre"	=>	"SOI pseudo-MOSFET",	"idutilisateur"	=>	403,	"idprojet"	=>	611),
				array("refinterneprojet"	=>	"13-104",	"titre"	=>	"Séchage super-critique et observation MEB de micro-objets",	"idutilisateur"	=>	409,	"idprojet"	=>	612),
				array("refinterneprojet"	=>	"13-105",	"titre"	=>	"PRIIM",	"idutilisateur"	=>	354,	"idprojet"	=>	613),
				array("refinterneprojet"	=>	"13-106",	"titre"	=>	"LCIV General",	"idutilisateur"	=>	352,	"idprojet"	=>	614),
				array("refinterneprojet"	=>	"13-107",	"titre"	=>	"LFCM General",	"idutilisateur"	=>	352,	"idprojet"	=>	615),
				array("refinterneprojet"	=>	"13-109",	"titre"	=>	"MOM",	"idutilisateur"	=>	348,	"idprojet"	=>	616),
				array("refinterneprojet"	=>	"13-110",	"titre"	=>	"SIFLEX",	"idutilisateur"	=>	376,	"idprojet"	=>	617),
				array("refinterneprojet"	=>	"13-111",	"titre"	=>	"NANORF",	"idutilisateur"	=>	272,	"idprojet"	=>	618),
				array("refinterneprojet"	=>	"13-112",	"titre"	=>	"FlexiZNO",	"idutilisateur"	=>	404,	"idprojet"	=>	619),
				array("refinterneprojet"	=>	"13-113",	"titre"	=>	"DIOPTRA",	"idutilisateur"	=>	67,	"idprojet"	=>	620),
				array("refinterneprojet"	=>	"13-114",	"titre"	=>	"MAGIE PDF",	"idutilisateur"	=>	392,	"idprojet"	=>	621),
				array("refinterneprojet"	=>	"13-115",	"titre"	=>	"BMS explortatoire impédance mécanique",	"idutilisateur"	=>	349,	"idprojet"	=>	622),
				array("refinterneprojet"	=>	"13-116",	"titre"	=>	"ANTARES",	"idutilisateur"	=>	215,	"idprojet"	=>	623),
				array("refinterneprojet"	=>	"13-117",	"titre"	=>	"nanorobot",	"idutilisateur"	=>	215,	"idprojet"	=>	624),
				array("refinterneprojet"	=>	"13-118",	"titre"	=>	"AUBAINE-PTA",	"idutilisateur"	=>	215,	"idprojet"	=>	625),
				array("refinterneprojet"	=>	"13-119",	"titre"	=>	"Prepatterned Substrate for UHV SiNW growth",	"idutilisateur"	=>	379,	"idprojet"	=>	626),
				array("refinterneprojet"	=>	"13-120",	"titre"	=>	"ACCESS",	"idutilisateur"	=>	375,	"idprojet"	=>	627),
				array("refinterneprojet"	=>	"13-121",	"titre"	=>	"GRAPHENE LTM",	"idutilisateur"	=>	338,	"idprojet"	=>	628),
				array("refinterneprojet"	=>	"13-122",	"titre"	=>	"Mott-RRAM IMN",	"idutilisateur"	=>	276,	"idprojet"	=>	629),
				array("refinterneprojet"	=>	"13-123",	"titre"	=>	"COPO-GaAs",	"idutilisateur"	=>	401,	"idprojet"	=>	630),
				array("refinterneprojet"	=>	"13-124",	"titre"	=>	"Molnanospin",	"idutilisateur"	=>	360,	"idprojet"	=>	631),
				array("refinterneprojet"	=>	"13-125",	"titre"	=>	"Josephson Junction Arrays",	"idutilisateur"	=>	411,	"idprojet"	=>	632),
				array("refinterneprojet"	=>	"13-126",	"titre"	=>	"3C SiC nanoFET",	"idutilisateur"	=>	388,	"idprojet"	=>	633),
				array("refinterneprojet"	=>	"13-127",	"titre"	=>	"MIME",	"idutilisateur"	=>	396,	"idprojet"	=>	634),
				array("refinterneprojet"	=>	"13-128",	"titre"	=>	"MIM3D",	"idutilisateur"	=>	401,	"idprojet"	=>	635),
				array("refinterneprojet"	=>	"13-129",	"titre"	=>	"GRAFOL",	"idutilisateur"	=>	356,	"idprojet"	=>	636),
				array("refinterneprojet"	=>	"13-131",	"titre"	=>	"GRAFLEX",	"idutilisateur"	=>	274,	"idprojet"	=>	637),
				array("refinterneprojet"	=>	"13-132",	"titre"	=>	"Smartcell",	"idutilisateur"	=>	8,	"idprojet"	=>	638),
				array("refinterneprojet"	=>	"13-133",	"titre"	=>	"Microtube",	"idutilisateur"	=>	8,	"idprojet"	=>	639),
				array("refinterneprojet"	=>	"13-134",	"titre"	=>	"POMME INEEL",	"idutilisateur"	=>	385,	"idprojet"	=>	640),
				array("refinterneprojet"	=>	"13-135",	"titre"	=>	"GUEPARD",	"idutilisateur"	=>	383,	"idprojet"	=>	641),
				array("refinterneprojet"	=>	"13-136",	"titre"	=>	"MAD-FIZ",	"idutilisateur"	=>	355,	"idprojet"	=>	642),
				array("refinterneprojet"	=>	"13-137",	"titre"	=>	"CoBISS-PTA",	"idutilisateur"	=>	135,	"idprojet"	=>	643),
				array("refinterneprojet"	=>	"13-138",	"titre"	=>	"PsS (Photonique sur Silicium)",	"idutilisateur"	=>	380,	"idprojet"	=>	644),
				array("refinterneprojet"	=>	"13-139",	"titre"	=>	"Nanoplast",	"idutilisateur"	=>	8,	"idprojet"	=>	645),
				array("refinterneprojet"	=>	"13-140",	"titre"	=>	"GRENADA",	"idutilisateur"	=>	338,	"idprojet"	=>	646),
				array("refinterneprojet"	=>	"13-141",	"titre"	=>	"LT-Nanomag",	"idutilisateur"	=>	267,	"idprojet"	=>	647),
				array("refinterneprojet"	=>	"13-142",	"titre"	=>	"UMI-LN2",	"idutilisateur"	=>	67,	"idprojet"	=>	648),
				array("refinterneprojet"	=>	"13-143",	"titre"	=>	"CMOS-MEMS",	"idutilisateur"	=>	408,	"idprojet"	=>	649),
				array("refinterneprojet"	=>	"13-144",	"titre"	=>	"SUPERNEMS",	"idutilisateur"	=>	386,	"idprojet"	=>	650),
				array("refinterneprojet"	=>	"13-145",	"titre"	=>	"FETSensSi NW",	"idutilisateur"	=>	343,	"idprojet"	=>	651),
				array("refinterneprojet"	=>	"13-146",	"titre"	=>	"Alumine nanoporeuse organisée par nanoimpression",	"idutilisateur"	=>	189,	"idprojet"	=>	652),
				array("refinterneprojet"	=>	"13-147",	"titre"	=>	"",	"idutilisateur"	=>	374,	"idprojet"	=>	653),
				array("refinterneprojet"	=>	"13-148",	"titre"	=>	"Plasma Siam",	"idutilisateur"	=>	336,	"idprojet"	=>	654),
				array("refinterneprojet"	=>	"13-149",	"titre"	=>	"Wafer Bonding for Optical and Nanofluidics Devices",	"idutilisateur"	=>	402,	"idprojet"	=>	655),
				array("refinterneprojet"	=>	"13-150",	"titre"	=>	"Nanofils II-VI",	"idutilisateur"	=>	359,	"idprojet"	=>	656),
				array("refinterneprojet"	=>	"13-151",	"titre"	=>	"CREAB-PTA",	"idutilisateur"	=>	371,	"idprojet"	=>	657),
				array("refinterneprojet"	=>	"13-152",	"titre"	=>	"TEMOIN",	"idutilisateur"	=>	353,	"idprojet"	=>	658),
				array("refinterneprojet"	=>	"13-153",	"titre"	=>	"Dimeci",	"idutilisateur"	=>	364,	"idprojet"	=>	659),
				array("refinterneprojet"	=>	"13-154",	"titre"	=>	"NIL LTM",	"idutilisateur"	=>	190,	"idprojet"	=>	660),
				array("refinterneprojet"	=>	"13-155",	"titre"	=>	"Spintronique NM",	"idutilisateur"	=>	368,	"idprojet"	=>	661),
				array("refinterneprojet"	=>	"13-156",	"titre"	=>	"Bolo-X",	"idutilisateur"	=>	380,	"idprojet"	=>	662),
				array("refinterneprojet"	=>	"13-157",	"titre"	=>	"SPY",	"idutilisateur"	=>	160,	"idprojet"	=>	663),
				array("refinterneprojet"	=>	"13-158",	"titre"	=>	"HYBRIDNANO",	"idutilisateur"	=>	375,	"idprojet"	=>	664),
				array("refinterneprojet"	=>	"13-159",	"titre"	=>	"Micro Cooler",	"idutilisateur"	=>	281,	"idprojet"	=>	665),
				array("refinterneprojet"	=>	"13-160",	"titre"	=>	"Cellulose Hybrid",	"idutilisateur"	=>	139,	"idprojet"	=>	666),
				array("refinterneprojet"	=>	"13-161",	"titre"	=>	"S-CPW",	"idutilisateur"	=>	405,	"idprojet"	=>	667),
				array("refinterneprojet"	=>	"13-162",	"titre"	=>	"FAME",	"idutilisateur"	=>	345,	"idprojet"	=>	668),
				array("refinterneprojet"	=>	"13-071",	"titre"	=>	"Effet Hall de spin ",	"idutilisateur"	=>	162,	"idprojet"	=>	669),
				array("refinterneprojet"	=>	"13-163",	"titre"	=>	"Neurosense",	"idutilisateur"	=>	406,	"idprojet"	=>	670),
				array("refinterneprojet"	=>	"13-164",	"titre"	=>	"MOULE QUARTZ",	"idutilisateur"	=>	189,	"idprojet"	=>	671),
				array("refinterneprojet"	=>	"13-165",	"titre"	=>	"INVENTIV",	"idutilisateur"	=>	140,	"idprojet"	=>	672),
				array("refinterneprojet"	=>	"13-166",	"titre"	=>	"I2FLEX",	"idutilisateur"	=>	345,	"idprojet"	=>	673),
				array("refinterneprojet"	=>	"13-167",	"titre"	=>	"TeraGaN",	"idutilisateur"	=>	350,	"idprojet"	=>	674),
				array("refinterneprojet"	=>	"13-168",	"titre"	=>	"mini-p",	"idutilisateur"	=>	62,	"idprojet"	=>	675),
				array("refinterneprojet"	=>	"13-169",	"titre"	=>	"SiPowLight",	"idutilisateur"	=>	395,	"idprojet"	=>	676),
				array("refinterneprojet"	=>	"13-170",	"titre"	=>	"N-POEM-PTA",	"idutilisateur"	=>	190,	"idprojet"	=>	677),
				array("refinterneprojet"	=>	"13-171",	"titre"	=>	"F.VOLPI",	"idutilisateur"	=>	407,	"idprojet"	=>	678),
				array("refinterneprojet"	=>	"13-172",	"titre"	=>	"Levitation diamagnetique sur micro-aimants",	"idutilisateur"	=>	391,	"idprojet"	=>	679)
);
for	($i	=	0;	$i	<	count($arrayprojetphase2);	$i++)	{
					$datedebutprojet =  date("m,d,Y");
					$projet =new Projetphase2datedebut($arrayprojetphase2[$i]['idprojet'],	$datedebutprojet);
					$manager->updateProjetdatdebutPhase2LTM($projet,$arrayprojetphase2[$i]['idprojet']);
}


BD::deconnecter();
