<?php

include '../class/Manager.php';
//FERMETURE DE LA CONNEXION
$db = BD::connecter();
$manager = new Manager($db);
include_once '../outils/toolBox.php';

$arrayProjetphase2 = 
array(
    array("idprojet"=>281,"refinterneprojet"=> "REN13-01", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2009", "dureeprojet" => 12, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 1, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>282,"refinterneprojet"=> "REN13-02", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2010", "dureeprojet" => 36, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>283,"refinterneprojet"=> "REN13-03", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2011", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>284,"refinterneprojet"=> "REN13-04", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2011", "dureeprojet" => 5, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>285,"refinterneprojet"=> "REN13-05", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2011", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>286,"refinterneprojet"=> "REN13-06", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "03/07/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>287,"refinterneprojet"=> "REN13-07", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 2, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 1, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>288,"refinterneprojet"=> "REN13-08", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2011", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>289,"refinterneprojet"=> "REN13-09", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 6, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>290,"refinterneprojet"=> "REN13-10", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 18, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>5,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>291,"refinterneprojet"=> "REN13-11", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 3, "idperiodicite_periodicite" => 2, "datestatutfini" => "01/03/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>292,"refinterneprojet"=> "REN13-12", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 3, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>6,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>293,"refinterneprojet"=> "REN13-13", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>6,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>294,"refinterneprojet"=> "REN13-14", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 18, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>295,"refinterneprojet"=> "REN13-15", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 1, "idperiodicite_periodicite" => "", "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>6,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>296,"refinterneprojet"=> "REN13-16", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 6, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>297,"refinterneprojet"=> "REN13-17", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>5,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>298,"refinterneprojet"=> "REN13-18", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 6, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>6,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>299,"refinterneprojet"=> "REN13-19", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 1, "idperiodicite_periodicite" => "", "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>8),
    array("idprojet"=>300,"refinterneprojet"=> "REN13-20", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 3, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/06/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>301,"refinterneprojet"=> "REN13-21", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 2, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/12/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>302,"refinterneprojet"=> "REN13-22", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => "", "idperiodicite_periodicite" => "", "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>303,"refinterneprojet"=> "REN13-23", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 3, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>304,"refinterneprojet"=> "REN13-24", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 3, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>305,"refinterneprojet"=> "REN13-25", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2012", "dureeprojet" => 3, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>5,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>306,"refinterneprojet"=> "REN13-26", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "02/04/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>307,"refinterneprojet"=> "REN13-27", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/06/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>6,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>308,"refinterneprojet"=> "REN13-28", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => 1, "datestatutfini" => "02/04/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>309,"refinterneprojet"=> "REN13-31", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>5,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>310,"refinterneprojet"=> "REN13-32", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>311,"refinterneprojet"=> "REN13-33", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 2, "idperiodicite_periodicite" => "", "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>8),
    array("idprojet"=>312,"refinterneprojet"=> "REN13-34", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>313,"refinterneprojet"=> "REN13-35", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => "", "datestatutfini" => "01/03/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>6),
    array("idprojet"=>314,"refinterneprojet"=> "REN13-36", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 6, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>315,"refinterneprojet"=> "REN13-37", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "02/04/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>316,"refinterneprojet"=> "REN13-39", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 14, "idperiodicite_periodicite" => 1, "datestatutfini" => "03/05/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>317,"refinterneprojet"=> "REN13-40", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => 1, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>318,"refinterneprojet"=> "REN13-41", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => 1, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>5,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>319,"refinterneprojet"=> "REN13-42", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>8),
    array("idprojet"=>320,"refinterneprojet"=> "REN13-43", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 6, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>321,"refinterneprojet"=> "REN13-44", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>322,"refinterneprojet"=> "REN13-47", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 9, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>323,"refinterneprojet"=> "REN13-48", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>324,"refinterneprojet"=> "REN13-49", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/06/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>325,"refinterneprojet"=> "REN13-50", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/06/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>6),
    array("idprojet"=>326,"refinterneprojet"=> "REN13-51", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>327,"refinterneprojet"=> "REN13-52", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/06/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>328,"refinterneprojet"=> "REN13-53", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/06/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>6),
    array("idprojet"=>329,"refinterneprojet"=> "REN13-54", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>330,"refinterneprojet"=> "REN13-55", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 4, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/09/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>331,"refinterneprojet"=> "REN13-56", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 6, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>332,"refinterneprojet"=> "REN13-57", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 5, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>333,"refinterneprojet"=> "REN13-58", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>334,"refinterneprojet"=> "REN13-59", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>5,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>335,"refinterneprojet"=> "REN13-60", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 3, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>336,"refinterneprojet"=> "REN13-61", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => 1, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" => 4 ,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>337,"refinterneprojet"=> "REN13-62", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "03/10/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>1,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>338,"refinterneprojet"=> "REN13-63", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>6,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>339,"refinterneprojet"=> "REN13-64", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => 1, "datestatutfini" => "03/10/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>340,"refinterneprojet"=> "REN13-65", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => 1, "datestatutfini" => "03/10/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>6),
    array("idprojet"=>341,"refinterneprojet"=> "REN13-66", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 3, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>3,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>342,"refinterneprojet"=> "REN13-67", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 7, "idperiodicite_periodicite" => 1, "datestatutfini" => "03/11/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>6),
    array("idprojet"=>343,"refinterneprojet"=> "REN13-68", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => "", "idperiodicite_periodicite" => "", "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>8),
    array("idprojet"=>344,"refinterneprojet"=> "REN13-69", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 3, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" => 4 ,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>345,"refinterneprojet"=> "REN13-70", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 3, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>6,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>346,"refinterneprojet"=> "REN13-71", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" => 4 ,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>347,"refinterneprojet"=> "REN13-72", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "01/01/2013", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>"","idstatutprojet_statutprojet"=>6),
    array("idprojet"=>348,"refinterneprojet"=> "REN13-73", "devtechnologique" => FALSE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 1, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>5,"idstatutprojet_statutprojet"=>8),
    array("idprojet"=>349,"refinterneprojet"=> "REN13-74", "devtechnologique" => TRUE, "datedebutprojet" => "01/01/2013", "dureeprojet" => 1, "idperiodicite_periodicite" => 2, "datestatutfini" => "", "idsourcefinancement_sourcefinancement" => 6, "idthematique_thematique" =>2,"idstatutprojet_statutprojet"=>8)

);

//$projet = new Projetphase1($idprojet, $titreProjet, $numProjet, $confidentiel, $descriptif, $dateprojet, $contexte, $idtypeprojet_typeprojet, $attachement, $acronyme);


for ($i = 0; $i < 2; $i++) {
    $projetphaseLAAS2 = new ProjetphaseLAAS2($arrayProjetphase2[$i]['idprojet'], $arrayProjetphase2[$i]['refinterneprojet'], $arrayProjetphase2[$i]['devtechnologique'], $arrayProjetphase2[$i]['dureeprojet'],$arrayProjetphase2[$i]['idperiodicite_periodicite'],$arrayProjetphase2[$i]['idsourcefinancement_sourcefinancement'],$arrayProjetphase2[$i]['idthematique_thematique'],$arrayProjetphase2[$i]['datedebutprojet'],$arrayProjetphase2[$i]['datestatutfini']);    
    echo'<pre>';print_r($projetphaseLAAS2);echo'</pre>';/*
    $manager->updateProjetphase2LAAS($projetphaseLAAS2,$arrayProjetphase2[$i]['idprojet']);
    $concerne = new Concerne(4, $arrayProjetphase2[$i]['idprojet'], $arrayProjetphase2[$i]['idstatutprojet_statutprojet'],'');
    $manager->updateConcerne($concerne, $arrayProjetphase2[$i]['idprojet']);*/
}

BD::deconnecter();
